name = "emocean-api"
main = "src/index.js"
compatibility_date = "2026-03-01"

# Daily cleanup cron - runs at 3am UTC
[triggers]
crons = ["0 3 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "emocean-db"
database_id = "6727c215-2fa8-42dc-9967-427f9a8fb262"
